ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# elasticsearch plugins 
#RUN plugin install ingest-geoip
#RUN /usr/share/elasticsearch/bin/plugin install --batch ingest-geoip
#RUN /usr/share/elasticsearch/bin/plugin install --batch ingest-user-agent
#RUN elasticsearch-plugin install --batch repository-gcs
#RUN elasticsearch-plugin install --batch analysis-icu,lang-js
